[project]
name = "marketdata"
version = "0.1.0"
description = "crypto"
authors = [
    {name = "Kun"}
]
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
